spring.application.name=bookMyShowJan26
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/bookmyshowjan26
spring.datasource.username=root
spring.datasource.password=root